# Generated by Django 3.1.3 on 2020-12-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOM', models.CharField(max_length=200)),
                ('Prenom', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=200)),
                ('Date_de_naissance', models.DateField(verbose_name='date de naissance')),
                ('Lieu_de_naissance', models.CharField(max_length=200)),
                ('Statut', models.CharField(max_length=200)),
            ],
        ),
    ]
