# Generated by Django 3.1.3 on 2021-01-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='NOM',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='Prenom',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='Statut',
            field=models.CharField(choices=[('Etudiant', 'Etudiant'), ('Professeur', 'Professeur'), ('VAC_EXT', 'VAC_EXT'), ('MCF', 'MCF'), ('VAC_INT', 'VAC_INT')], max_length=200),
        ),
    ]
