# Generated by Django 3.1.3 on 2021-01-05 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiant', '0002_auto_20210105_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='Statut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Etudiant.statut'),
        ),
    ]
