# Generated by Django 3.1.3 on 2021-01-06 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiant', '0003_auto_20210105_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='Statut',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Etudiant.statut'),
        ),
    ]
